#!/bin/bash

minutes_arg=${1-10}
back_arg=${2-"soon"}

_minutes_result=""
function minutes() {
    if [[ $1 -eq 1 ]]; then
        _minutes_result="$1 minute"
    else
        _minutes_result="$1 minutes"
    fi
}

for ((i=$minutes_arg; i>=1; i--))
do
    minutes $i
    curl -d  "{\"id\": -$RANDOM, \"contents\": \"<span style=\\\"color: red;\\\">Kotoed is going down for mainteanance in ${_minutes_result}! <br/> Please finish all you work. <br/> We will be back ${back_arg}.</span>\"}" http://localhost:9000/debug/eventbus/kotoed.api.notification.push.broadcast.render\?publish\=true
    sleep 60
done

curl -d  "{\"id\": -$RANDOM, \"contents\": \"<span style=\\\"color: red;\\\">OK, we have warned you.</span>\"}" http://localhost:9000/debug/eventbus/kotoed.api.notification.push.broadcast.render\?publish\=true

tput bel